#server:
#  port: 8080
#
#
#spring:
#  profiles:
#    active: qa
#
#
#---
#
#
#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/mydbname
#    password: 25B22T.com
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#welcome:
#  message: Welcome to CUET CSE
#
#
#---
#
#
#spring:
#  profiles: qa
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/mydbname-qa
#    password: 25B22T.com
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#welcome:
#  message: Welcome to CUET CSE
#
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/mydbname-prod
#    password: 25B22T.com
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#welcome:
#  message: Welcome to CUET CSE
